# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Intro to PHS"
  url = "intro-to-phs"
  weight = 1
  identifier = "intro-to-phs-parent"
  
  [[main]]
  name = "Intro to PHS Slides"
  url = "/welcome-slides/PHSSummrCamp_introduction.pdf"
  parent = "intro-to-phs-parent"

[[main]]
  name = "Intro to R"
  url = "intro-to-r"
  weight = 2
  identifier = "intro-to-r-parent"
  
  [[main]]
    name = "Intro to R Slides"
    url = "/intro-to-r/PHS_SummR_Camp_Intro_to_R_2020.pdf"
    parent = "intro-to-r-parent"
    weight = 1
    
  [[main]]
    name = "Github Repo"
    url = "https://github.com/jrcordes/Intro_to_R_SummR_Camp_2020"
    parent = "intro-to-r-parent"
    weight = 2

[[main]]
  name = "Notation"
  url = "notation"
  weight = 3
  identifier = "notation-parent"
  
  [[main]]
    name = "Notation Slides (pdf)"
    url = "/notation-slides/PHSSummrCamp_mathematicalNotation.pdf"
    parent = "notation-parent"
    weight = 1
  
  [[main]]
    name = "Sweave Guide (pdf)"
    url = "/sweave-guide/guide.pdf"
    parent = "notation-parent"
    weight = 2

[[main]]
  name = "Math"
  url = "math-review"
  weight = 4
  identifier = "math-review-parent"
  
  [[main]]
    name = "Math Slides (html)"
    url = "/math-review-slides/math_review.html"
    parent = "math-review-parent"
    weight = 1
  
  [[main]]
    name = "Math Slides (pdf)"
    url = "/math-review-slides/math_review.pdf"
    parent = "math-review-parent"
    weight = 2

  [[main]]
    name = "Math R Code"
    url = "/math-review-r-code/math_review_code.R"
    parent = "math-review-parent"
    weight = 3
  
  [[main]]
    name = "Math Annotations"
    url = "/math-review-slides/SummR-Camp-Math-review-notes.pdf"
    parent = "math-review-parent"
    weight = 4

[[main]]
  name = "Probability"
  url = "prob-review"
  weight = 5
  identifier = "prob-review-parent"
  
  [[main]]
    name = "Probability Slides (pdf)"
    url = "/prob-slides/SummRCamp_2020_ProbStats.pdf"
    parent = "prob-review-parent"
    weight = 1
  
  [[main]]
    name = "Probability Annotated (pdf)"
    url = "/prob-slides/prob_annotated_slides.pdf"
    parent = "prob-review-parent"
    weight = 3

[[main]]
  name = "Regression"
  url = "regressionEx"
  weight = 6
  identifier = "regExParent"
  
  [[main]]
    name = "Reg Slides (html)"
    url = "/regressionSlides/slides.html"
    parent = "regExParent"
    weight = 1
    
  [[main]]
    name = "Reg Slides (pdf)"
    url = "/regressionSlides/slides.pdf"
    parent = "regExParent"
    weight = 2
  
  [[main]]
    name = "ExRcise #1"
    url = "regressionEx1"
    parent = "regExParent"
    weight = 3
    
  [[main]]
    name = "ExRcise #2"
    url = "regressionEx2"
    parent = "regExParent"
    weight = 4
  
  [[main]]
    name = "Exercise R code"
    url = "/regressionEx-r-scripts/reg-exercises-R-code.zip"
    parent = "regExParent"
    weight = 5
    
[[main]]
  name = "Warm-ups"
  url = "warmupParent"
  identifier = "warmupParent"
  weight = 10

  [[main]]
    name = "Wednesday/Thursday"
    url = "https://www.overleaf.com/7572393255xbgsdqhqwjdj"
    parent = "warmupParent"




# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
